name: custom_text_widget
description: A customizable text widget package with pre-defined font weights and easy styling options.
version: 1.0.0
homepage: https://github.com/raian-ruku/custom_text_widget

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  test: ^1.24.0

flutter:
  fonts:
    - family: CustomTextFont
      fonts:
        - asset: fonts/YourFont-Regular.ttf
