import 'package:flutter/material.dart';
import '../custom_text_widget.dart';

class Text100 extends CustomText {
  const Text100(
    String text, {
    Key? key,
    double? size,
    Color? color,
    double? letterSpacing,
    FontStyle? fontStyle,
    TextOverflow? overflow,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    double? decorationThickness,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? height,
    String? fontFamily,
  }) : super(
          text,
          key: key,
          size: size,
          color: color,
          letterSpacing: letterSpacing,
          fontWeight: FontWeight.w100,
          fontStyle: fontStyle,
          overflow: overflow,
          maxLines: maxLines,
          textAlign: textAlign,
          decoration: decoration,
          decorationThickness: decorationThickness,
          decorationColor: decorationColor,
          decorationStyle: decorationStyle,
          height: height,
          fontFamily: fontFamily,
        );
}

class Text200 extends CustomText {
  const Text200(
    String text, {
    Key? key,
    double? size,
    Color? color,
    double? letterSpacing,
    FontStyle? fontStyle,
    TextOverflow? overflow,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    double? decorationThickness,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? height,
    String? fontFamily,
  }) : super(
          text,
          key: key,
          size: size,
          color: color,
          letterSpacing: letterSpacing,
          fontWeight: FontWeight.w200,
          fontStyle: fontStyle,
          overflow: overflow,
          maxLines: maxLines,
          textAlign: textAlign,
          decoration: decoration,
          decorationThickness: decorationThickness,
          decorationColor: decorationColor,
          decorationStyle: decorationStyle,
          height: height,
          fontFamily: fontFamily,
        );
}

class Text300 extends CustomText {
  const Text300(
    String text, {
    Key? key,
    double? size,
    Color? color,
    double? letterSpacing,
    FontStyle? fontStyle,
    TextOverflow? overflow,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    double? decorationThickness,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? height,
    String? fontFamily,
  }) : super(
          text,
          key: key,
          size: size,
          color: color,
          letterSpacing: letterSpacing,
          fontWeight: FontWeight.w300,
          fontStyle: fontStyle,
          overflow: overflow,
          maxLines: maxLines,
          textAlign: textAlign,
          decoration: decoration,
          decorationThickness: decorationThickness,
          decorationColor: decorationColor,
          decorationStyle: decorationStyle,
          height: height,
          fontFamily: fontFamily,
        );
}

class Text400 extends CustomText {
  const Text400(
    String text, {
    Key? key,
    double? size,
    Color? color,
    double? letterSpacing,
    FontStyle? fontStyle,
    TextOverflow? overflow,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    double? decorationThickness,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? height,
    String? fontFamily,
  }) : super(
          text,
          key: key,
          size: size,
          color: color,
          letterSpacing: letterSpacing,
          fontWeight: FontWeight.w400,
          fontStyle: fontStyle,
          overflow: overflow,
          maxLines: maxLines,
          textAlign: textAlign,
          decoration: decoration,
          decorationThickness: decorationThickness,
          decorationColor: decorationColor,
          decorationStyle: decorationStyle,
          height: height,
          fontFamily: fontFamily,
        );
}

class Text500 extends CustomText {
  const Text500(
    String text, {
    Key? key,
    double? size,
    Color? color,
    double? letterSpacing,
    FontStyle? fontStyle,
    TextOverflow? overflow,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    double? decorationThickness,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? height,
    String? fontFamily,
  }) : super(
          text,
          key: key,
          size: size,
          color: color,
          letterSpacing: letterSpacing,
          fontWeight: FontWeight.w500,
          fontStyle: fontStyle,
          overflow: overflow,
          maxLines: maxLines,
          textAlign: textAlign,
          decoration: decoration,
          decorationThickness: decorationThickness,
          decorationColor: decorationColor,
          decorationStyle: decorationStyle,
          height: height,
          fontFamily: fontFamily,
        );
}

class Text600 extends CustomText {
  const Text600(
    String text, {
    Key? key,
    double? size,
    Color? color,
    double? letterSpacing,
    FontStyle? fontStyle,
    TextOverflow? overflow,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    double? decorationThickness,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? height,
    String? fontFamily,
  }) : super(
          text,
          key: key,
          size: size,
          color: color,
          letterSpacing: letterSpacing,
          fontWeight: FontWeight.w600,
          fontStyle: fontStyle,
          overflow: overflow,
          maxLines: maxLines,
          textAlign: textAlign,
          decoration: decoration,
          decorationThickness: decorationThickness,
          decorationColor: decorationColor,
          decorationStyle: decorationStyle,
          height: height,
          fontFamily: fontFamily,
        );
}

class Text700 extends CustomText {
  const Text700(
    String text, {
    Key? key,
    double? size,
    Color? color,
    double? letterSpacing,
    FontStyle? fontStyle,
    TextOverflow? overflow,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    double? decorationThickness,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? height,
    String? fontFamily,
  }) : super(
          text,
          key: key,
          size: size,
          color: color,
          letterSpacing: letterSpacing,
          fontWeight: FontWeight.w700,
          fontStyle: fontStyle,
          overflow: overflow,
          maxLines: maxLines,
          textAlign: textAlign,
          decoration: decoration,
          decorationThickness: decorationThickness,
          decorationColor: decorationColor,
          decorationStyle: decorationStyle,
          height: height,
          fontFamily: fontFamily,
        );
}

class Text800 extends CustomText {
  const Text800(
    String text, {
    Key? key,
    double? size,
    Color? color,
    double? letterSpacing,
    FontStyle? fontStyle,
    TextOverflow? overflow,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    double? decorationThickness,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? height,
    String? fontFamily,
  }) : super(
          text,
          key: key,
          size: size,
          color: color,
          letterSpacing: letterSpacing,
          fontWeight: FontWeight.w800,
          fontStyle: fontStyle,
          overflow: overflow,
          maxLines: maxLines,
          textAlign: textAlign,
          decoration: decoration,
          decorationThickness: decorationThickness,
          decorationColor: decorationColor,
          decorationStyle: decorationStyle,
          height: height,
          fontFamily: fontFamily,
        );
}

class Text900 extends CustomText {
  const Text900(
    String text, {
    Key? key,
    double? size,
    Color? color,
    double? letterSpacing,
    FontStyle? fontStyle,
    TextOverflow? overflow,
    int? maxLines,
    TextAlign? textAlign,
    TextDecoration? decoration,
    double? decorationThickness,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? height,
    String? fontFamily,
  }) : super(
          text,
          key: key,
          size: size,
          color: color,
          letterSpacing: letterSpacing,
          fontWeight: FontWeight.w900,
          fontStyle: fontStyle,
          overflow: overflow,
          maxLines: maxLines,
          textAlign: textAlign,
          decoration: decoration,
          decorationThickness: decorationThickness,
          decorationColor: decorationColor,
          decorationStyle: decorationStyle,
          height: height,
          fontFamily: fontFamily,
        );
}
